#ifndef ERROR_CODE_H_INCLUDED
#define ERROR_CODE_H_INCLUDED

#define print_error(error_code) LOGD( "\n\n[EEROR %s: %d]file %s on line %d\n\n", #error_code, error_code, __FILE__, __LINE__);

enum Error
{
	PTG_NOT_INIT_ERROR = 0,
	PTG_GET_VERTEX_ERROR,
	PTG_LEVEL_ERROR,


	SERIAL_RX_BUFFER_SIZE_ERROR,
	POINT_OUT_MAP_ERROR,

	PTR_IS_NULL_ERROR,
	DATA_LEN_OUT_OF_RANGE_ERROR,
	LIDAR_DATA_LEN_WRONG_ERROR,
	CALCULATE_ERROR,
	FILE_OPEN_FAILED_ERROR,
	PATH_PLAN_ERROR,
	CHARGE_ALIGN_ERROR,

	RESERVER0=100,

	NORMAL_ERROR,
};

#endif // WINDOWSDEF_H_INCLUDED
